### PR TITLE
Added script for binding stop_code to district

### PR DESCRIPTION
**Pull request by man-netcat**

### CODE REVIEW

**Review by JoeyHen — CHANGES_REQUESTED** [review]
Could you change this to make a function that just returns the json object? Now i have to read the output which isn't very clean

**Comment by rickteuthof** [comment]
Changes approved!

**Review by man-netcat — COMMENTED** [review]
Changes approved!

**Review by JoeyHen — APPROVED** [review]

**Comment by JoeyHen** [comment]
Nice!

**Pull request merged**
